---
- hosts: all
  pre_tasks:
    - name: Update apt cache it if hasn't been updated within the last day
      apt: update_cache=yes cache_valid_time=86400
      sudo: yes

    - name: Install Ubuntu packages
      apt: pkg={{ item }}
      sudo: yes
      with_items:
        - git
        - python
        - python-dev
        - python-pip

    - name: Install Python-related packages
      pip: name={{ item }}
      sudo: yes
      with_items:
        - pyzmq
        - tornado
        - ipython
        - jsonschema
        #- numpy
        #- scipy
        #- matplotlib
  roles:
    - vim
    - bash-aliases
