syntax on
set hlsearch
set ignorecase
set smartcase
set viminfo='10,\"100,:20,%,n~/.viminfo
set scrolloff=5
set textwidth=10000
set expandtab
set shiftwidth=4
"set colorcolumn=80 " Draw a red vertical line at column 80

" Jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
